# -*- coding: utf-8 -*-
"""111.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NB_aMrL_8HJo-E28XRkk0J0MU_ukGFjO
"""

from google.colab import drive
drive.mount('/content/drive')
url = '/content/drive/MyDrive/AIDM_7360_project/games.db'

DB_FILE_PATH = url
db_path = url

"""This is a functional documentation for a **Steam Game Data Analysis and Automatic Report Generation Tool** based on Python and SQLite. This script aims to extract basic game information and statistical data from a local database, combine it with preset text templates, and automatically generate multi-dimensional game assessment reports.

---

# Steam Game Data Analysis & Report Tool Functional Description

## 1. Project Overview
This module is primarily used to automate the generation of analysis reports for Steam games. By reading game metadata (such as developer, tags, ratings, online player count, price, etc.) from an SQLite database and text templates stored in the database, it processes specific algorithmic logic to generate reports covering six dimensions: Manufacturer Analysis, Type Positioning, Popularity Analysis, Platform Fit, Value Assessment, and Comprehensive Recommendation.

## 2. Core Functional Modules

### 2.1 Data Access Layer
This layer is responsible for interacting with the SQLite database to extract raw data.

*   **`get_game_data(db_path, game_name)`**:
    *   **Function**: Queries detailed information about a game based on its name.
    *   **Logic**: Executes complex SQL `JOIN` queries to aggregate the `Game` table with related tables like Developer, Publisher, Genre, and Tag.
    *   **Output**: Returns a dictionary containing all game fields and concatenated strings (e.g., multiple tags separated by commas).
*   **`get_all_templates(db_path)`**:
    *   **Function**: Loads all report templates from the `templates` table in the database.
    *   **Advantage**: Achieves **separation of copy and code**, allowing report text modification by updating the database without changing Python code.

### 2.2 Business Logic Layer
This layer contains 6 core analysis functions responsible for cleaning, judging, and calculating raw data, then filling the results into templates.

1.  **Manufacturer's Card (`generate_developer_card`)**:
    *   **Analysis Dimensions**: Number of positive reviews, positive rate, peak concurrent users (CCU).
    *   **Output**: Assesses the reputation of the developer/publisher (e.g., "Golden Brand" or "Controversial") and market appeal.
2.  **Type Positioning (`generate_type_positioning`)**:
    *   **Analysis Dimensions**: Positive rate ratio, game Tags.
    *   **Output**: Determines the game's status among similar works (e.g., "A classic not to be missed" or "Not recommended").
3.  **Recent Popularity (`generate_recent_popularity`)**:
    *   **Analysis Dimensions**: Average/Median playtime in the last two weeks, Estimated owners.
    *   **Logic**: Parses owner count range strings (e.g., "100,000 - 200,000") to judge player activity, trends of new/old players, and community scale.
4.  **Multi-platform Fit (`generate_multi_platform_fit`)**:
    *   **Analysis Dimensions**: OS support (Win/Mac/Linux), Simplified Chinese support.
    *   **Output**: Assesses device compatibility and language friendliness.
5.  **Value King (`generate_value_king`)**:
    *   **Analysis Dimensions**: Historical average playtime, user score, price.
    *   **Algorithm**: Calculates cost-performance index `(Average Playtime * Score) / (Price + 1)` to judge if it is "Great Value".
6.  **Comprehensive Recommendation (`generate_comprehensive_recommendation`)**:
    *   **Analysis Dimensions**: Score, Peak CCU, Playtime, Price, DLC count.
    *   **Algorithm**: Weighted scoring formula `(Score*15) + (log(CCU)*5) + (Playtime/4) - (Price/5)`.
    *   **Output**: Provides a 3-5 star comprehensive recommendation rating.

### 2.3 Controller & Presentation Layer
*   **`generate_all_reports_for_game(...)`**:
    *   Acts as the main entry function, coordinating data fetching and logic dispatch.
    *   Generates specific types of reports based on the passed `select_templates` list.
    *   Formats print output, including headers and separators.

## 3. Database Requirement (Schema)
The code execution relies on a specific SQLite database structure. The presumed schema is:

*   **Base Data Tables**:
    *   `Game` (AppID, Name, Price, Positive, Negative, Peak_ccu, Average_playtime_2weeks, Estimated_owners, User_score, etc.)
    *   `Developer`, `Publisher`, `Genre`, `Tag` (and their corresponding intermediate association tables like `Game_Developer`, etc.)
*   **Template Table**:
    *   `templates` (Fields: `report_name`, `template_text`)

## 4. Usage Example

```python
# Assuming database file is 'steam_games.db'
db_path = 'steam_games.db'
game_name = 'Elden Ring'

# Define list of report types to generate
selected_reports = [
    'developer_card',           # Manufacturer's Card
    'recent_popularity',        # Recent Popularity
    'comprehensive_recommendation' # Comprehensive Recommendation
]

# Execute generation
generate_all_reports_for_game(game_name, db_path, selected_reports)
"""

import sqlite3
import math
import time
from typing import List, Dict, Any, Optional


# --- Step 1: Fetch All Data ---

def get_game_data(db_path: str, game_name: str):
    conn = None
    try:
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Merge lists
        query = """
        SELECT
            g.*,
            GROUP_CONCAT(DISTINCT d.Name) AS Developers,
            GROUP_CONCAT(DISTINCT p.Name) AS Publishers,
            GROUP_CONCAT(DISTINCT gn.Name) AS Genres,
            GROUP_CONCAT(DISTINCT t.Name) AS Tags
        FROM Game g
        LEFT JOIN Game_Developer gd ON g.AppID = gd.AppID
        LEFT JOIN Developer d ON gd.DeveloperID = d.DeveloperID
        LEFT JOIN Game_Publisher gp ON g.AppID = gp.AppID
        LEFT JOIN Publisher p ON gp.PublisherID = p.PublisherID
        LEFT JOIN Game_Genre gg ON g.AppID = gg.AppID
        LEFT JOIN Genre gn ON gg.GenreID = gn.GenreID
        LEFT JOIN Game_Tag gt ON g.AppID = gt.AppID
        LEFT JOIN Tag t ON gt.TagID = t.TagID
        WHERE g.Name = ?
        GROUP BY g.AppID;
        """

        cursor.execute(query, (game_name,))
        game_data = cursor.fetchone()

        if game_data:
            return dict(game_data)
        else:
            print(f"Error: Cannot find '{game_name}'.")
            return None
    except sqlite3.Error as e:
        print(f"Database operation error: {e}")
        return None
    finally:
        if conn:
            conn.close()


def get_all_templates(db_path: str):
    # Fetch all report templates from the templates table in the database.
    conn = None
    templates = {}
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        cursor.execute("SELECT report_name, template_text FROM templates")
        for row in cursor.fetchall():
            templates[row[0]] = row[1]
        return templates
    except sqlite3.Error as e:
        print(f"Error: {e}")
        return {}
    finally:
        if conn:
            conn.close()


# --- Step 2: Define Logic Checks ---

def generate_developer_card(data: Dict[str, Any], template: str) :
    """No.1 Manufacturer's Card"""
    """
    This work was developed by {Publishers}.
    The developer is {word_of_mouth} {strength}. As a result,
    {Name} was highly anticipated and trustworthy even before its release.
    """
    # Logic check

    total = data.get('Positive', 0) + data.get('Negative', 0)
    if data.get('Positive', 0) > 10000:
        mouth_word = "widely condemned"
    elif total > 0 and data.get('Positive', 0) / total > 0.7:
        mouth_word = "A golden brand guaranteeing quality"
    else:
        mouth_word = "worthy of attention"

    if data.get('Peak_ccu', 0) > 20000:
        strength = "its games are usually attract a large number of players."
    else:
        strength = "Their games are generally based on the player's personal preferences"

    # --- Modification Start ---
    # Added Publishers parameter in .format() to fill the {Publishers} placeholder in the template
    report = template.format(
        Developers=data.get('Developers', 'Unknown developer'),
        Publishers=data.get('Publishers', 'Unknown developer'),  # <--- This added line is key
        word_of_mouth =mouth_word,
        strength=strength,
        Name=data.get('Name', 'the game')
    )
    # --- Modification End ---

    return f"--- Manufacturer's business card ---\n{report}\n"


def generate_type_positioning(data: Dict[str, Any], template: str) :
    """No.2 Type Positioning"""
    """
    {Name} is a {Genres} game
    {Tags}.
    the game is {status} among all games on Steam.
    """
    # Logic check
    positive, negative = data.get('Positive', 0), data.get('Negative', 0)
    total = positive + negative
    if total == 0:
        status = "Generally, it is not recommended to try."
    else:
        ratio = positive / total
        if ratio > 0.8:
            status = f"It ranks among the top games in its genre.in {data.get('Genres', 'This type')},A classic that enthusiasts shouldn't miss"
        elif ratio > 0.5:
            status = "Good, worth a try"
        else:
            status = "Generally, it is not recommended to try."
    if data.get('Tags') == "NULL":
        Tag = f"that incorporates elements such as {data.get('Tags')}"
    else:
        Tag = ''
    # Fill template
    report = template.format(
        Name=data.get('Name', 'the game'),
        Genres=data.get('Genres', 'many types'),
        Tags=Tag,
        status=status
    )
    return f"--- Type positioning ---\n{report}\n"


def generate_recent_popularity(data: Dict[str, Any], template: str) :
    """No.3 Recent Popularity"""
    """
    Although it has been on sale for some time, {Name} has {activity},
    {engagement} in the last two weeks. Accumulated {Recommendations} recommendations,
    {trends}. The number of players is approximately {Estimated_owners}, {scale_ratings},
    which means you can still easily find like-minded or opponents.
    """
    # Logic check
    avg_2w = data.get('Average_playtime_2weeks', 0)
    median_2w = data.get('Median_playtime_2weeks', 0)
    owners = data.get('Estimated_owners', '')

    if avg_2w > 20:
        activity = "It still maintains a very high level of player activity"
    else:
        activity = "Player activity is average"

    if median_2w > 10:
        engagement = "Most players have been playing continuously recently"
    else:
        engagement = "Most players have not been playing regularly recently"

    if avg_2w > median_2w:
        trends = "New players continue to pour in"
    else:
        trends = "there are few new players"

    try:
        # Extract numeric part from string
        parts = owners.split(' - ')
        max_owners = int(parts[-1])
    except (ValueError, IndexError):
        # Return default value if format does not match or is empty
        return "data type error"

    if max_owners <= 20000:
        scale_ratings =  "this is a unique, niche gem, waiting to be discovered by discerning players"
    elif max_owners <= 50000:
        scale_ratings = "the community is growing steadily, and this is a new game with great potential"
    elif max_owners <= 100000:
        scale_ratings = "as a promising new title, it is becoming a favorite among more and more players"
    elif max_owners <= 500000:
        scale_ratings = "this game has garnered significant attention and boasts a broad player base"
    elif max_owners <= 2000000:
        scale_ratings = "as a popular and excellent game, it has successfully attracted the love of a large number of players"
    elif max_owners <= 10000000:
        scale_ratings = "this is a phenomenal success, with a huge player community"
    else:  # Greater than 10,000,000
        scale_ratings = "with a massive player base of tens of millions, this is a legendary masterpiece that has stood the test of time"

    # Fill template
    report = template.format(
        Name=data.get('Name', 'this game'),
        activity=activity,
        engagement=engagement,
        Recommendations=data.get('Recommendations', 0),
        trends=trends,
        Estimated_owners=owners,
        scale_ratings=scale_ratings
    )
    return f"--- Recent popularity ---\n{report}\n"


def generate_multi_platform_fit(data: Dict[str, Any], template: str):
    """No.4 Multi-platform Fit"""
    """
    {Support_level}{Chinese_support}. Enjoy this {Genres} masterpiece no matter what device you are using.
    """
    # Logic check
    p_count = sum([data.get('Windows', 0), data.get('Mac', 0), data.get('Linux', 0)])

    if p_count == 3:
        Support_level = "Perfect support for all platforms"
    else:
        Support_level = "This game is not supported on all platforms"

    if "Simplified Chinese" in data.get('Supported_languages', ''):
        Chinese_support = "，it also provides full Simplified Chinese support"
    else:
        Chinese_support = "，it don't provides  Simplified Chinese support"

    # Fill template
    report = template.format(
        Name=data.get('Name', 'the game'),
        Support_level=Support_level,
        Chinese_support=Chinese_support,
        Genres=data.get('Genres', 'this type')
    )
    return f"--- Multi-platform compatibility ---\n{report}\n"


def generate_value_king(data: Dict[str, Any], template: str) :
    """No.5 Value King"""
    """
    {Name} offers immersive experience at {Price} yuan,
    value for money {rating}. The game received {Positive} positive reviews.
    This is undoubtedly a safe choice for players who like {Genres}.
    """
    # Logic check
    avg_play = data.get('Average_playtime_forever', 0)
    score = data.get('User_score', 0)
    price = data.get('Price', 0)

    pp_index = (avg_play * score) / (price + 1)

    if pp_index > 1000 and price < 50:
        rating = "Super cost-effective"
    else:
        rating = "Average value for money"

    # Fill template
    report = template.format(
        Name=data.get('Name', 'the game'),
        Price=price,
        Average_playtime_forever=avg_play,
        rating=rating,
        Positive=data.get('Positive', 0),
        Genres=data.get('Genres', 'this type')
    )
    return f"--- The king of cost performance ---\n{report}\n"


def generate_comprehensive_recommendation(data: Dict[str, Any], template: str) :
    """No.6 Comprehensive Recommendation"""
    """
    Based on multi-dimensional analysis such as ratings, online peak, game duration and price,
    {Name} received the {final_recommendation}. {Follow_up_content}, suitable for players seeking {Genres} types.
    """
    # Logic check
    score = data.get('User_score', 0)
    ccu = data.get('Peak_ccu', 1)
    playtime = data.get('Average_playtime_forever', 0)
    price = data.get('Price', 0)

    comp_score = (score * 15) + (math.log(ccu+1) * 5) + (min(playtime, 200) / 4) - (price / 5)

    if comp_score > 150:
        final_recommendation = "Five-star recommendation, excellent performance in all aspects"
    elif comp_score >= 100:
        final_recommendation = "Four-star recommendation, an excellent game"
    else:
        final_recommendation = "Samsung recommends this; it's a game worth trying"

    # Fill template
    # Assuming the template needs a {Follow_up_content} placeholder, hardcoding an example here
    if data.get('DLC_count') != 0:
        Follow_up_content = "It attracted a large number of players with its excellent game design and rich content"
    else:
        Follow_up_content = "Unfortunately.there is follow-up content for this game"

    report = template.format(
        Name=data.get('Name', 'the game'),
        final_recommendation=final_recommendation,
        Follow_up_content=Follow_up_content,
        Genres=data.get('Genres', 'this type')
    )
    return f"--- Comprehensive recommendation ---\n{report}\n"


# --- Step 3: Define Report Generation ---

def generate_all_reports_for_game(game_name: str, db_path: str, select_templates: List[str]):
    """
    Generate all selected reports for the specified game, templates dynamically loaded from the database.
    """
    # 1. Get all templates
    all_templates = get_all_templates(db_path)
    if not all_templates:
        print("Error: Cannot load report templates from database, program terminated.")
        return

    # 2. Get data for the specified game
    game_data = get_game_data(db_path, game_name)
    if not game_data:
        return

    # 3. Map report names to their generator functions
    report_functions = {
        'developer_card': generate_developer_card,
        'type_positioning': generate_type_positioning,
        'recent_popularity': generate_recent_popularity,
        'multi_platform_fit': generate_multi_platform_fit,
        'value_king': generate_value_king,
        'comprehensive_recommendation': generate_comprehensive_recommendation,
    }

    print(f"==================== 《{game_name}》report ====================\\n")

    # 4. Iterate through selected templates, generate and print reports
    for template_name in select_templates:
        report_func = report_functions.get(template_name)
        template_text = all_templates.get(template_name)

        if report_func and template_text:
            report = report_func(game_data, template_text)
            print(report)
        else:
            print(f"--- error：can,t find '{template_name}' ---\\n")

    print("============================== end ==============================")

"""This is a functional documentation for an **Interactive Steam Game Filtering and Recommendation System** based on Python and SQLite.

This code complements the previous "Automatic Report Generation Tool": the previous section focused on **"Deep Analysis of a Single Game"**, while this section focuses on **"Screening Target Games from a Massive Database"**.

---

# Steam Game Interactive Filtering System Functional Description

## 1. Project Overview
This module implements a console-based Interactive Dashboard, allowing users to quickly locate Steam games that meet specific needs from an SQLite database through multi-level conditional filtering.

Unlike traditional linear questionnaires, this system uses a **Non-linear Menu Design**. After selecting a core genre, users can freely adjust filtering conditions such as visuals, gameplay, price, and configuration, and view the number of remaining games in real-time.

## 2. Core Functional Modules

### 2.1 Dynamic SQL Generation Layer
The code defines 19 SQL generation functions from `Q1` to `QF`, covering all aspects of game filtering.
*   **Mechanism**: Each function receives the user's option index and returns a specific SQL `SELECT` statement fragment and corresponding parameter list.
*   **Coverage Dimensions**:
    *   **Basic Attributes**: Genre, Release Year.
    *   **Visuals & Presentation**: Art Style (Pixel/Realistic, etc.), Perspective (First/Third Person).
    *   **Content & Theme**: Worldview (Cyberpunk/Fantasy, etc.), Narrative Style, Content Rating.
    *   **Gameplay Experience**: Atmosphere, Difficulty, Multiplayer Mode Types.
    *   **Technology & Hardware**: VR Support, Controller Support, System Compatibility (Win/Mac/Linux).
    *   **Economic Attributes**: Price Range, DLC Count, Promotion Strategy.
    *   **Evaluation Metrics**: Positive Rate, Total Playtime, Replay Value.

### 2.2 Core Filtering Engine
*   **Intersection Operation (`execute_intersect`)**:
    *   **Logic**: This is an "AND" relationship. The system connects SQL statements of all user-activated filters using the `INTERSECT` keyword.
    *   **Effect**: Only Game IDs that satisfy all selected conditions are retained. For example: (Genre=RPG) **AND** (Price<10) **AND** (Positive Rate>90%).
*   **Real-time Feedback**: Every time a user applies a new filter condition, the system immediately queries the database, calculates, and displays the **"Remaining Matched Games Count"**.

### 2.3 Interactive Dashboard UI
This is the core part of user experience (`filter_game` function):
*   **Intelligent Dependency Logic**: The system has a built-in `logic` dictionary that automatically hides or recommends specific options based on the initial Genre selected by the user.
    *   *Example*: If "Puzzle" is selected, the system automatically hides "Perspective Selection"; if "MMO" is selected, the system marks "Multiplayer Mode" as recommended.
*   **Regret Mechanism (Undo/Retry)**:
    *   In `enter_sub_menu`, if a user's choice results in 0 matches, the system issues a warning and allows the user to **Undo** the last operation to avoid a dead end.
*   **Non-linear Operation**: Users can jump between 9 main category menus at will to modify conditions.

### 2.4 Result Presentation & Sorting
*   **Multi-dimensional Sorting**: Supports sorting by "Price Low to High", "Rating High to Low", and "Release Date New to Old".
*   **Dynamic Calculation**: Calculates positive rate (`(Positive/Total)*100`) in real-time during output, as the raw database may only store absolute numbers.
*   **Structured Output**: The function finally returns a list of dictionaries containing Game Name, Positive Rate, and Price for subsequent program calls.

## 3. Linkage with Previous Code (Automatic Report Generation)

These two code segments constitute a complete **"Select-Analyze"** workflow:

1.  **Prerequisite Step (This Code) - Filter**:
    *   User faces tens of thousands of games and doesn't know what to play.
    *   Filter through this tool (e.g., Find a "2024 release, Pixel style, Roguelike, Overwhelmingly Positive" game).
    *   Resulting in a game list (e.g., `['Balatro', 'Animal Well']`).

2.  **Subsequent Step (Previous Code) - Analyst**:
    *   User is interested in the screened results and wants a detailed analysis.
    *   Pass the screened game name to the `generate_all_reports_for_game` function in the previous code.
    *   Generate "Manufacturer's Card", "Value Analysis", and "Comprehensive Recommendation Report" for that game.

### Linkage Code Example

```python
# 1. Use the filter to find a list of games meeting criteria
# Run filter_game(), assuming user interacts and finally screens out results
filtered_results = filter_game()
# filtered_results structure example: [{'Name': 'Elden Ring', 'PositiveRate': 92, ...}, ...]

# 2. Generate detailed text reports for the top 3 screened games
db_path = 'steam_games.db'
report_templates = ['type_positioning', 'value_king', 'comprehensive_recommendation']

if filtered_results:
    print("\n🚀 Generating in-depth reports for selected games:\n")
    for game_info in filtered_results[:3]: # Take only the first three
        game_name = game_info['Name']
        # Call the function defined in the previous code
        generate_all_reports_for_game(game_name, db_path, report_templates)
else:
    print("No games found matching criteria, report cannot be generated.")
```

## 4. Code Logic Flowchart

1.  **Initialization**: Connect Database ->
2.  **Step 1**: Mandatory Selection of Core Genre ->
3.  **Loop (Dashboard)**:
    *   Display Menu (Visuals/Gameplay/Price, etc.)
    *   User Enters Sub-menu -> Answers Questions
    *   Generate SQL -> `INTERSECT` Query
    *   **IF** Results > 0: Save Condition, Update Remaining Count
    *   **ELSE** (Results=0): Prompt Undo or Keep
4.  **End**: User Selects "Query and Finish" ->
5.  **Output**: Select Sorting Method -> Print Detailed List -> **Return Data to Caller**.

## 5. Highlights Summary
*   **SQL Injection Defense**: Although a local tool, all SQL construction uses parameterized queries `(?, ?)`, which is safe and standard.
*   **Fault Tolerance Design**: Powerful input checking (`get_user_input`) and fallback mechanisms when filter results are 0 greatly improve user experience.
*   **Modularity**: Filter logic for each dimension is encapsulated independently, non-interfering, and easy to extend with new filter conditions (e.g., adding "Steam Deck Support" only requires adding one function).
"""

import sqlite3
import os

# ==========================================
# 0. Basic Configuration & Tools
# ==========================================
db_path = url


def get_conn(path):
    if os.path.exists(path):
        return sqlite3.connect(path)
    else:
        print(f"❌ Error: Can't find {path}")
        return None


def get_user_input(prompt_text, max_val):
    while True:
        val = input(f"   {prompt_text} (0-{max_val}, Enter to skip): ")
        if val.strip() == "": return 0
        try:
            val_int = int(val)
            if val_int >= 0: return val_int
        except ValueError:
            pass
        print(f"   ❌ Invalid input.")


# ==========================================
# 1. SQL Generation Functions (Kept unchanged, collapsed to save space)
# ==========================================
# ... (Fully reused previous functions, defined fully here for execution) ...

def Q1_Genre_SQL(choice):
    if choice == 0: return None

    sql = """
 SELECT g.AppID
    FROM Game g
    JOIN Game_Genre gg ON g.AppID = gg.AppID
    JOIN Genre gen ON gg.GenreID = gen.GenreID
    WHERE
        -- 1. Action
        (? = 1 AND gen.Name = 'Action') OR

        -- 2. Adventure
        (? = 2 AND gen.Name = 'Adventure') OR

        -- 3. Casual
        (? = 3 AND gen.Name = 'Casual') OR

        -- 4. RPG
        (? = 4 AND gen.Name = 'RPG') OR

        -- 5. Strategy
        (? = 5 AND gen.Name = 'Strategy') OR

        -- 6. Simulation
        (? = 6 AND gen.Name = 'Simulation') OR

        -- 7. Indie
        (? = 7 AND gen.Name = 'Indie') OR

        -- 8. Sports
        (? = 8 AND gen.Name = 'Sports') OR

        -- 9. Racing
        (? = 9 AND gen.Name = 'Racing') OR

        -- 10. Massively Multiplayer
        (? = 10 AND gen.Name = 'Massively Multiplayer') OR

        -- 11. Free to Play
        (? = 11 AND gen.Name IN ('Free to Play', 'Free To Play')) OR

        -- 12. Early Access
        (? = 12 AND gen.Name = 'Early Access') OR

        -- 13. Mature & Violent
        (? = 13 AND gen.Name IN ('Gore', 'Violent', 'Nudity', 'Sexual Content')) OR

        -- 14. Movie & Video
        (? = 14 AND gen.Name IN ('Movie', 'Episodic', 'Short', 'Documentary', '360 Video')) OR

        -- 15. Education & Training
        (? = 15 AND gen.Name IN ('Education', 'Tutorial', 'Software Training')) OR

        -- 16. Design & Modeling
        (? = 16 AND gen.Name IN ('Design & Illustration', 'Animation & Modeling')) OR

        -- 17. Photo & Video Prod
        (? = 17 AND gen.Name IN ('Photo Editing', 'Video Production')) OR

        -- 18. Audio Production
        (? = 18 AND gen.Name = 'Audio Production') OR

        -- 19. Dev & Web
        (? = 19 AND gen.Name IN ('Game Development', 'Web Publishing')) OR

        -- 20. Utilities & Accounting
        (? = 20 AND gen.Name IN ('Utilities', 'Accounting'))

    GROUP BY g.AppID
    """
    return sql, [choice] * 20


def Q2_1_Style_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Pixel Graphics', 'Retro')) OR
    (? = 2 AND t.Name IN ('8-bit Music', 'Old School')) OR
    (? = 3 AND t.Name IN ('1980s', '1990''s')) OR
    (? = 4 AND t.Name = 'Hand-drawn') OR
    (? = 5 AND t.Name IN ('Cartoony', 'Cartoon')) OR
    (? = 6 AND t.Name = 'Comic Book') OR
    (? = 7 AND t.Name = 'Anime') OR
    (? = 8 AND t.Name = 'Realistic') OR
    (? = 9 AND t.Name = 'Stylized') OR
    (? = 10 AND t.Name = 'Voxel') OR
    (? = 11 AND t.Name IN ('Abstract', 'Surreal')) OR
    (? = 12 AND t.Name = 'Minimalist') OR
    (? = 13 AND t.Name = 'Cinematic')
    GROUP BY g.AppID
    """
    return sql, [choice] * 13


def Q2_2_Perspective_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name = 'First-Person') OR
    (? = 2 AND t.Name = 'Third Person') OR
    (? = 3 AND t.Name IN ('Top-Down', 'Isometric')) OR
    (? = 4 AND t.Name IN ('Side Scroller', '2D', '2.5D'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 4


def Q3_1_Theme_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name = 'Cyberpunk') OR
    (? = 2 AND t.Name IN ('Space', 'Space Sim', 'Aliens')) OR
    (? = 3 AND t.Name IN ('Futuristic', 'Post-apocalyptic')) OR
    (? = 4 AND t.Name IN ('Robots', 'Mechs')) OR
    (? = 5 AND t.Name IN ('Fantasy', 'Medieval', 'Dragons', 'Magic')) OR
    (? = 6 AND t.Name IN ('Mythology', 'Supernatural')) OR
    (? = 7 AND t.Name IN ('Dark Fantasy', 'Gothic')) OR
    (? = 8 AND t.Name = 'Steampunk') OR
    (? = 9 AND t.Name = 'Modern') OR
    (? = 10 AND t.Name IN ('Historical', 'World War II', 'World War I')) OR
    (? = 11 AND t.Name IN ('Military', 'War', 'Tactical')) OR
    (? = 12 AND t.Name IN ('Crime', 'Detective', 'Noir')) OR
    (? = 13 AND t.Name = 'Lovecraftian') OR
    (? = 14 AND t.Name IN ('Zombies', 'Survival Horror')) OR
    (? = 15 AND t.Name = 'Vampire') OR
    (? = 16 AND t.Name IN ('Post-apocalyptic', 'Dystopian'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 16


def Q3_2_Story_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Story Rich', 'Narrative')) OR
    (? = 2 AND t.Name IN ('Visual Novel', 'Interactive Fiction')) OR
    (? = 3 AND t.Name IN ('Choices Matter', 'Choose Your Own Adventure')) OR
    (? = 4 AND t.Name IN ('Horror', 'Psychological Horror', 'Mystery')) OR
    (? = 5 AND t.Name IN ('Comedy', 'Dark Humor', 'Funny', 'Parody')) OR
    (? = 6 AND t.Name IN ('Drama', 'Emotional', 'Romance')) OR
    (? = 7 AND t.Name IN ('Philosophical', 'Psychological'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 7


def Q4_1_Mood_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Casual', 'Funny', 'Cute', 'Colorful')) OR
    (? = 2 AND t.Name IN ('Action', 'Thriller', 'Fast-Paced')) OR
    (? = 3 AND t.Name IN ('Horror', 'Psychological Horror', 'Mystery')) OR
    (? = 4 AND t.Name IN ('Cozy', 'Wholesome', 'Relaxing', 'Family Friendly')) OR
    (? = 5 AND t.Name IN ('Dark', 'Dark Fantasy', 'Gore', 'Violent')) OR
    (? = 6 AND t.Name IN ('Epic', 'Lore-Rich', 'Cinematic')) OR
    (? = 7 AND t.Name IN ('Atmospheric', 'Immersive', 'Walking Simulator'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 7


def Q4_2_Difficulty_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Casual', 'Relaxing')) OR
    (? = 2 AND t.Name IN ('Difficult', 'Challenging', 'Hard')) OR
    (? = 3 AND t.Name IN ('Souls-like', 'Permadeath', 'Unforgiving', 'Brutal')) OR
    (? = 4 AND t.Name IN ('Adjustable Difficulty', 'Difficulty Options'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 4


def Q5_1_Multiplayer_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Local Co-Op', 'Local Multiplayer', '4 Player Local')) OR
    (? = 2 AND t.Name IN ('Online Co-Op', 'Co-op Campaign')) OR
    (? = 3 AND t.Name IN ('PvP', 'Competitive', 'Versus')) OR
    (? = 4 AND t.Name IN ('Team-Based', 'MOBA', 'Hero Shooter')) OR
    (? = 5 AND t.Name = 'Battle Royale') OR
    (? = 6 AND t.Name IN ('MMORPG', 'Massively Multiplayer')) OR
    (? = 7 AND t.Name = 'Social Deduction') OR
    (? = 8 AND t.Name = 'Singleplayer')
    GROUP BY g.AppID
    """
    return sql, [choice] * 8


def Q6_1_Features_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Moddable', 'Level Editor')) OR
    (? = 2 AND t.Name IN ('Replay Value', 'Multiple Endings')) OR
    (? = 3 AND t.Name IN ('Great Soundtrack', 'Audio Production'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 3


def Q6_2_Hardware_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('VR', 'VR Only')) OR
    (? = 2 AND t.Name IN ('Controller', 'Full controller support'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 2


def Q6_3_Content_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    JOIN Game_Tag gt ON g.AppID = gt.AppID
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND t.Name IN ('Family Friendly', 'Wholesome')) OR
    (? = 2 AND t.Name IN ('Mature', 'Sexual Content', 'Nudity', 'Hentai')) OR
    (? = 3 AND t.Name IN ('Violent', 'Gore', 'Blood')) OR
    (? = 4 AND t.Name IN ('Horror', 'Psychological Horror'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 4


def Q7_1_Price_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    WHERE (? = 1 AND g.Price = 0 AND EXISTS (
    SELECT 1
    FROM Game_Tag gt
    JOIN Tag t ON gt.TagID = t.TagID
    WHERE gt.AppID = g.AppID AND t.Name = 'Free to Play')) OR

    (? = 2 AND g.Price < 10 AND g.Price > 0) OR
    (? = 3 AND g.Price BETWEEN 10 AND 30) OR
    (? = 4 AND g.Price BETWEEN 30 AND 60) OR
    (? = 5 AND g.Price > 60)
    GROUP BY g.AppID
    """
    return sql, [choice] * 5


def Q7_2_DLC_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    WHERE (? = 1 AND g.DLC_count = 0) OR
    (? = 2 AND g.DLC_count BETWEEN 1 AND 5) OR
    (? = 3 AND g.DLC_count > 5)
    GROUP BY g.AppID
    """
    return sql, [choice] * 3


def Q8_1_Review_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    WHERE (? = 1 AND (g.Positive + g.Negative) >= 500 AND (g.Positive * 100.0) / (g.Positive + g.Negative) >= 95) OR
    (? = 2 AND (g.Positive + g.Negative) > 0 AND (g.Positive * 100.0) / (g.Positive + g.Negative) >= 80) OR
    (? = 3 AND (g.Positive + g.Negative) > 0 AND (g.Positive * 100.0) / (g.Positive + g.Negative) >= 70) OR
    (? = 4 AND (g.Positive + g.Negative) > 0 AND (g.Positive * 100.0) / (g.Positive + g.Negative) >= 40)
    GROUP BY g.AppID
    """
    return sql, [choice] * 4


def Q9_1_Playtime_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    WHERE (? = 1 AND g.Average_playtime_forever < 600) OR
    (? = 2 AND g.Average_playtime_forever BETWEEN 600 AND 1800) OR
    (? = 3 AND g.Average_playtime_forever BETWEEN 1800 AND 6000) OR
    (? = 4 AND g.Average_playtime_forever > 6000)
    GROUP BY g.AppID
    """
    return sql, [choice] * 4


def Q9_2_Replay_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    LEFT JOIN Game_Tag gt ON g.AppID = gt.AppID
    LEFT JOIN Tag t ON gt.TagID = t.TagID
    WHERE (? = 1 AND g.Achievements > 20) OR
    (? = 2 AND t.Name LIKE '%Multiple Endings%') OR
    (? = 3 AND t.Name LIKE '%Procedural Generation%') OR
    (? = 4 AND (t.Name LIKE '%Moddable%' OR t.Name LIKE '%Level Editor%')) OR
    (? = 5 AND (t.Name LIKE '%Multiplayer%' OR t.Name LIKE '%Co-op%'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 5


def Q10_1_OS_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID
    FROM Game g
    WHERE (? = 1 AND g.Windows = 1 AND g.Mac = 0 AND g.Linux = 0) OR
    (? = 2 AND g.Windows = 0 AND g.Mac = 1 AND g.Linux = 0) OR
    (? = 3 AND g.Windows = 0 AND g.Mac = 0 AND g.Linux = 1) OR
    (? = 4 AND (g.Windows + g.Mac + g.Linux) >= 2)
    GROUP BY g.AppID
    """
    return sql, [choice] * 4


def Q10_2_Lang_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID FROM Game g
    WHERE (? = 1 AND g.Supported_languages LIKE '%Simplified Chinese%') OR
    (? = 2 AND g.Supported_languages LIKE '%English%') OR
    (? = 3 AND g.Supported_languages LIKE '%Japanese%')
    GROUP BY g.AppID
    """
    return sql, [choice] * 3


def QF_1_Year_SQL(choice):
    if choice == 0: return None
    sql = """
    SELECT g.AppID FROM Game g
    WHERE (? = 1 AND g.Release_date LIKE '%2024%') OR
    (? = 2 AND (g.Release_date LIKE '%2022%' OR g.Release_date LIKE '%2023%' OR g.Release_date LIKE '%2024%')) OR
    (? = 3 AND (g.Release_date NOT LIKE '%2022%' AND g.Release_date NOT LIKE '%2023%' AND g.Release_date NOT LIKE '%2024%'))
    GROUP BY g.AppID
    """
    return sql, [choice] * 3

# ==========================================
# Implementation of Add, Delete, and Modify functions
# ==========================================

def add_new_game(conn):
    print("\n--- 🆕 Add New Game (Demo Mode) ---")
    name = input("Enter Game Name: ").strip()
    if not name: return

    try:
        price = float(input("Enter Price (USD): "))
    except ValueError:
        print("❌ Invalid price.")
        return

    # For simplicity, we automatically generate a large ID to avoid conflicts
    try:
        cur = conn.cursor()
        # Get current max ID + 1
        cur.execute("SELECT MAX(AppID) FROM Game")
        max_id = cur.fetchone()[0]
        new_id = max_id + 1 if max_id else 99990000

        # Insert data (other fields given default values, demonstrating core principle)
        sql = """
        INSERT INTO Game (AppID, Name, Price, Release_date, Positive, Negative, User_score, Estimated_owners)
        VALUES (?, ?, ?, 'Jan 1, 2025', 0, 0, 0, "unknow")
        """
        cur.execute(sql, (new_id, name, price))
        conn.commit()
        print(f"✅ Success! Game '{name}' added with ID {new_id}.")
    except Exception as e:
        print(f"❌ Error: {e}")


def delete_game(conn):
    print("\n--- 🗑️ Delete Game ---")
    name = input("Enter the EXACT Game Name to delete: ").strip()
    if not name: return

    try:
        cur = conn.cursor()
        # Check if exists
        cur.execute("SELECT AppID FROM Game WHERE Name = ?", (name,))
        row = cur.fetchone()
        if not row:
            print(f"❌ Game '{name}' not found.")
            return

        # Execute delete
        cur.execute("DELETE FROM Game WHERE Name = ?", (name,))
        conn.commit()
        print(f"✅ Success! Game '{name}' (ID: {row[0]}) has been deleted.")
    except Exception as e:
        print(f"❌ Error: {e}")

def update_game_price(conn):
    print("\n--- ✏️ Update Game Price ---")
    name = input("Enter the EXACT Game Name to update: ").strip()

    try:
        cur = conn.cursor()
        cur.execute("SELECT Price FROM Game WHERE Name = ?", (name,))
        row = cur.fetchone()
        if not row:
            print(f"❌ Game '{name}' not found.")
            return

        print(f"ℹ️ Current Price: ${row[0]}")
        new_price = float(input("Enter New Price: "))

        cur.execute("UPDATE Game SET Price = ? WHERE Name = ?", (new_price, name))
        conn.commit()
        print(f"✅ Success! Price updated to ${new_price}.")
    except Exception as e:
        print(f"❌ Error: {e}")
# ==========================================
# 2. Core Logic and Processing Functions
# ==========================================

def execute_intersect(conn, active_filters):
    """Run filters"""
    if not active_filters: return None
    full_sqls = []
    full_params = []
    for key, (sql, params) in active_filters.items():
        full_sqls.append(sql)
        full_params.extend(params)

    final_sql = " \nINTERSECT\n ".join(full_sqls)# Intersection
    try:
        cur = conn.cursor()
        cur.execute(final_sql, full_params)
        return set(row[0] for row in cur.fetchall())
    except sqlite3.Error as e:
        print(f"SQL Execution Error: {e}")
        return set()


def show_final_results_sorted(conn, app_id_set, sort_choice):
    if app_id_set is not None and len(app_id_set) == 0:
        print("\n❌ Result: No games found with current filters.")
        return []

    print("\n" + "=" * 80)
    print(f"🎉 Filtering Complete! Generating Final List...")

    where_clause = ""
    if app_id_set is not None:
        ids = list(app_id_set)
        if len(ids) == 1:
            where_clause = f"WHERE g.AppID = {ids[0]}"
        else:
            where_clause = f"WHERE g.AppID IN {tuple(ids)}"

    order_clause = ""
    sort_name = ""
    if sort_choice == 1:
        order_clause = "ORDER BY g.Price ASC, g.Positive DESC"
        sort_name = "💰 Price: Low to High"
    elif sort_choice == 2:
        order_clause = "ORDER BY g.Positive DESC, g.User_score DESC"
        sort_name = "⭐ Rating: High to Low"
    elif sort_choice == 3:
        order_clause = "ORDER BY g.Release_date DESC"
        sort_name = "📅 Release Date: Recent to Old"
    else:
        order_clause = "ORDER BY g.Positive DESC"
        sort_name = "Default Sorting"

    print(f"📊 Sorting By: {sort_name}")
    print("=" * 100)

    # SQL Updated: Now fetches Negative reviews to calculate the percentage
    sql = f"""
    SELECT g.Name, g.Price, g.Metacritic_score, g.Positive, g.Negative, g.Release_date
    FROM Game g
    {where_clause}
    {order_clause}
    LIMIT 20
    """

    try:
        cur = conn.cursor()
        cur.execute(sql)
        rows = cur.fetchall()

        # Print Table Header
        print(f"{'Name':<40} | {'Price':<8} | {'Score':<5} | {'Positive Rate':<13} | {'Release Date'}")
        print("-" * 100)

        structured_results = []

        for row in rows:
            name_full = row[0]
            # Truncate name for display if too long
            name_display = row[0][:38] + '..' if len(row[0]) > 38 else row[0]
            price = f"${row[1]}" if row[1] > 0 else "Free"
            score = row[2] if row[2] else "-"

            # --- Calculate Positive Rate ---
            pos = row[3]
            neg = row[4]
            total_reviews = pos + neg
            pos_rate = int((pos / total_reviews) * 100) if total_reviews > 0 else 0

            # Print Row
            print(f"{name_display:<40} | {price:<8} | {score:<5} | {pos_rate}% ({pos})   | {row[5]}")

            # --- Save Data for Return ---
            # We save it as a dictionary so the chart function can use 'PositiveRate'
            structured_results.append({
                'Name': name_full,
                'PositiveRate': pos_rate,
                'Price': row[1]
            })

        print("-" * 100)

        # Return the list of DICTIONARIES (Name + Stats)
        return structured_results

    except Exception as e:
        print(f"Error: {e}")
        return []


def enter_sub_menu(conn, menu_name, questions, active_filters):
    """Enter sub-menu configuration (With 0-result Undo)"""
    print(f"\n--- Configuring {menu_name} ---")

    # 1. Calculate base count on entry
    base_ids = execute_intersect(conn, active_filters)
    base_count = len(base_ids) if base_ids is not None else 0
    print(f"ℹ️ Current base match: {base_count} games")

    if base_count == 0 and len(active_filters) > 0:
        print(
            "⚠️ Warning: You already have 0 matches. Further filtering might be useless. Consider undoing previous choices.")

    # 2. Loop through questions
    for q_key, q_data in questions.items():
        print(f"\n>> {q_data['title']}")
        opt_list = [f"[{k}] {v}" for k, v in q_data['options'].items()]
        for i in range(0, len(opt_list), 2):
            print("   " + "  |  ".join(opt_list[i:i + 2]))

        # Show current status
        if q_key in active_filters:
            print(f"   [Selected: Active]")

        max_k = max(q_data['options'].keys()) if q_data['options'] else 0
        ans = get_user_input("Select (0 to keep/skip)", max_k)

        if ans != 0:
            # === A. Backup old state ===
            had_old_value = q_key in active_filters
            old_value = active_filters.get(q_key)

            # === B. Try apply new filter ===
            active_filters[q_key] = q_data['func'](ans)

            # === C. Calculate new count ===
            current_ids = execute_intersect(conn, active_filters)
            count = len(current_ids) if current_ids is not None else 0

            # === D. Judge and Remedy ===
            if count > 0:
                print(f"   ✅ Filter applied | 📊 Remaining matches: {count} games")
            else:
                print(f"   ⚠️  Oops! This choice resulted in 0 matches.")
                print("   [1] ↩️ Undo selection (Recommended)")
                print("   [2] 🔒 Keep it (I want this specific criteria)")

                fix_choice = input("   >> Select action (1/2): ")

                if fix_choice == '2':
                    print("   🆗 Empty result retained.")
                else:
                    # Execute Undo
                    print("   ↩️ Undoing...")
                    if had_old_value:
                        active_filters[q_key] = old_value  # Restore old value
                    else:
                        del active_filters[q_key]  # Delete if didn't exist

                    # Recalculate
                    restored_ids = execute_intersect(conn, active_filters)
                    r_count = len(restored_ids) if restored_ids is not None else 0
                    print(f"      📊 Restored matches: {r_count} games")

    input("\nPress Enter to return to Dashboard...")


# ==========================================
# 3. Main Workflow (Dashboard Mode)
# ==========================================

def filter_game():
    conn = get_conn(db_path)
    if not conn: return

    print("*************************************************")
    print("*      Speed Dashboard Filter (Dashboard Mode)        *")
    print("*************************************************")

    # Store all active filters: {'q1': (sql, params), 'q2_1': ...}
    active_filters = {}

    # Option Data
    OPT = {
        'q1': {
            1: 'Action',
            2: 'Adventure',
            3: 'Casual',
            4: 'RPG',
            5: 'Strategy',
            6: 'Simulation',
            7: 'Indie',
            8: 'Sports',
            9: 'Racing',
            10: 'Massively Multiplayer',
            11: 'Free to Play',
            12: 'Early Access',
            13: 'Mature ',
            14: 'Episodic',
            15: 'Education ',
            16: 'Modeling',
            17: 'Video Production',
            18: 'Audio Production',
            19: 'Game Dev & Web',
            20: 'Utilities'
        },
        'q2_1': {1: 'Pixel', 2: '8-bit', 3: '80s/90s', 4: 'Hand-drawn', 5: 'Cartoon', 6: 'Comic', 7: 'Anime',
                 8: 'Realistic', 9: 'Stylized', 10: 'Voxel', 11: 'Abstract', 12: 'Minimalist', 13: 'Cinematic'},
        'q2_2': {1: 'First-Person', 2: 'Third Person', 3: 'Top-Down', 4: 'Side Scroller'},
        'q3_1': {1: 'Cyberpunk', 2: 'Space', 3: 'Post-apoc', 4: 'Robots', 5: 'Fantasy', 6: 'Mythology',
                 7: 'Dark Fantasy', 8: 'Steampunk', 9: 'Modern', 10: 'History/War', 11: 'Military', 12: 'Crime',
                 13: 'Lovecraft', 14: 'Zombies', 15: 'Vampire', 16: 'Dystopian'},
        'q3_2': {1: 'Story Rich', 2: 'Visual Novel', 3: 'Choices Matter', 4: 'Horror/Mystery', 5: 'Comedy', 6: 'Drama',
                 7: 'Philosophical'},
        'q4_1': {1: 'Casual/Cute', 2: 'Action/Thriller', 3: 'Horror', 4: 'Cozy', 5: 'Dark/Gore', 6: 'Epic',
                 7: 'Atmospheric'},
        'q4_2': {1: 'Casual', 2: 'Difficult', 3: 'Souls-like', 6: 'Adjustable'},
        'q5_1': {1: 'Local Co-Op', 2: 'Online Co-Op', 3: 'PvP', 4: 'Team-Based', 5: 'Battle Royale', 6: 'MMO',
                 7: 'Social Deduction', 8: 'Singleplayer'},
        'q6_1': {1: 'Moddable', 2: 'Replay Value', 3: 'Great Soundtrack'},
        'q6_2': {1: 'VR', 2: 'Controller'},
        'q6_3': {1: 'Family Friendly', 2: 'Mature/Nudity', 3: 'Violent/Gore', 4: 'Horror'},
        'q7_1': {1: 'Free to Play', 2: '<10$', 3: '10-30$', 4: '30-60$', 5: '>60$'},
        'q7_2': {1: 'full version(no DLC)', 2: 'A small amount of DLC', 3: 'Lots of DLC'},
        'q8_1': {1: 'rave reviews(95%+)', 2: 'Particularly favorable(80%+)', 3: 'Mostly good reviews(70%+)', 4: 'Opinions are mixed(40%+)'},
        'q9_1': {1: '<10h', 2: '10-30h', 3: '30-100h', 4: '>100h'},
        'q9_2': {1: 'achievement party(>20)', 2: 'multiple endings', 3: 'randomly generated', 4: 'Creative workshop', 5: 'Contains multiplayer elements'},
        'q10_1': {1: 'Win Only', 2: 'Mac Only', 3: 'Linux Only', 4: 'Cross-platform'},
        'q10_2': {1: 'Simplified Chinese', 2: 'English', 3: 'Japanese'},
        'qf_1': {1: '2024', 2: '2022-2024', 3: '<2022'}
    }

    # Logic Control Group
    logic = {
        # Needs perspective (Action, Adventure, RPG, Simulation, Sports, Racing, MMO)
        'need_perspective': [1, 2, 4, 6, 8, 9, 10],

        # Story Rich (Adventure, RPG, Movies)
        'need_story': [2, 4, 14],

        # Hide Difficulty (Casual, Sim, Sports, Movie, and all software categories 15-20)
        'hide_difficulty': [3, 6, 8, 14, 15, 16, 17, 18, 19, 20],

        # Must be multiplayer (MMO)
        'need_multiplayer': [10],

        # Hardware related (Simulation, Racing)
        'need_hardware': [6, 9]
    }

    # --- 1. Mandatory Step: Select Core Genre ---
    print("\n=== step 1 : genre of games ===")
    opt_list = [f"[{k}] {v}" for k, v in OPT['q1'].items()]
    for i in range(0, len(opt_list), 2): print("   " + "  |  ".join(opt_list[i:i + 2]))

    current_genre = get_user_input("Your choice", 20)
    if current_genre == 0:
        print("❌ Please select a genre to continue.")
        return

    # Store into filters
    active_filters['q1'] = Q1_Genre_SQL(current_genre)

    # Define 6 tag filter modules to determine if activated
    module_keys_map = {
        '1': ['q2_1', 'q2_2'],
        '2': ['q3_1', 'q3_2', 'q6_3'],
        '3': ['q4_1', 'q4_2'],
        '4': ['q5_1'],
        '5': ['q6_1', 'q6_2'],
        '6': ['q7_1', 'q7_2']
    }

    # --- 2. Dashboard Main Loop ---
    while True:
        # Calculate count of 6 tag modules, activated count
        selected_modules = []
        for m_id, keys in module_keys_map.items():
            # If active_filters contains any key under this module, consider the module selected
            if any(k in active_filters for k in keys):
                selected_modules.append(m_id)

        # Check if full (>=2)
        is_full = len(selected_modules) >= 2


        # Dynamically build menu (Decide whether to show tips based on Genre)
        print("\n" + "=" * 40)
        print(f"   🎛️  Filter Dashboard (Selected: {OPT['q1'][current_genre]})")
        print("=" * 40)

        # Check logic status
        show_persp = current_genre in logic['need_perspective']
        show_story = current_genre in logic['need_story']
        show_diff = current_genre not in logic['hide_difficulty']
        show_multi = current_genre in logic['need_multiplayer']
        show_hard = current_genre in logic['need_hardware']

        # Print menu items, show mark if configured
        def get_status_icon(m_id, related_keys):
            # 1. If module selected, show ✅
            if m_id in selected_modules:
                return "✅ (Selected)"
            # 2. If not selected but full (is_full is True), show ❌
            elif m_id in module_keys_map and is_full:
                return "❌ (Unavailable)"
            # 3. Neither selected nor full, or 7-9 non-restricted modules, show empty or original logic
            else:
                return "✅" if any(k in active_filters for k in related_keys) else ""

        # Note: first arg of get_status_icon is string '1', '2'...
        print(f"[1] Vision and Presentation {get_status_icon('1', ['q2_1', 'q2_2'])}")
        print(f"[2] Content and themes {get_status_icon('2', ['q3_1', 'q3_2', 'q6_3'])}")
        print(f"[3] Experience and atmosphere {get_status_icon('3', ['q4_1', 'q4_2'])}")
        print(f"[4] Social and multiplayer {get_status_icon('4', ['q5_1'])}")
        print(f"[5] Technology and functionality {get_status_icon('5', ['q6_1', 'q6_2'])}")
        print(f"[6] Price and DLC  {get_status_icon('6', ['q7_1', 'q7_2'])}")

        # 7-9 Unrestricted, use original logic
        print(f"[7] Evaluation and Duration {get_status_icon('7', ['q8_1', 'q9_1', 'q9_2'])}")
        print(f"[8] compatibility     {get_status_icon('8', ['q10_1', 'q10_2'])}")
        print(f"[9] Release time   {get_status_icon('9', ['qf_1'])}")
        print("-" * 40)
        print("[0] 🔍 Complete and query (GO!)")

        choice = input("\n>> Please select the module to configure. (0-9): ")
        # A. Exit Check
        if choice == '0':
            break
        # B. Intercept Check (Independent if block)
        if choice in module_keys_map:
            # If module not selected (new choice) and full
            if choice not in selected_modules and is_full:
                print(f"\n⚠️  Warning: You can only select 2 modules from [1-6].")
                print(f"   Please clear an existing selection first (go into a checked module and Undo).")
                input("   Press Enter to continue...")
                continue # Skip loop, don't enter if/elif below
        # C. Menu Entry Logic (Note: must use if here, not elif connected to above)
        if choice == '1':  # Visuals
            qs = {'q2_1': {'title': '[Q2.1] Art Style', 'options': OPT['q2_1'], 'func': Q2_1_Style_SQL}}
            if show_persp:
                qs['q2_2'] = {'title': '[Q2.2] Perspective & Camera', 'options': OPT['q2_2'],
                              'func': Q2_2_Perspective_SQL}
            enter_sub_menu(conn,"Visuals & Presentation", qs, active_filters)

        elif choice == '2':  # Content
            qs = {'q3_1': {'title': '[Q3.1] World Setting', 'options': OPT['q3_1'], 'func': Q3_1_Theme_SQL},
                  'q6_3': {'title': '[Q6.3] Content Rating', 'options': OPT['q6_3'], 'func': Q6_3_Content_SQL}}
            if show_story:
                qs['q3_2'] = {'title': '[Q3.2] Storytelling Approach', 'options': OPT['q3_2'], 'func': Q3_2_Story_SQL}
            enter_sub_menu(conn,"Content & Themes", qs, active_filters)

        elif choice == '3':  # Experience
            qs = {'q4_1': {'title': '[Q4.1] Overall Atmosphere', 'options': OPT['q4_1'], 'func': Q4_1_Mood_SQL}}
            if show_diff:
                qs['q4_2'] = {'title': '[Q4.2] Difficulty Level', 'options': OPT['q4_2'], 'func': Q4_2_Difficulty_SQL}
            enter_sub_menu(conn,"Experience & Atmosphere", qs, active_filters)

        elif choice == '4':  # Multiplayer
            qs = {
                'q5_1': {'title': '[Q5.1] Multiplayer Mode Type', 'options': OPT['q5_1'], 'func': Q5_1_Multiplayer_SQL}}
            enter_sub_menu(conn,"Social & Multiplayer", qs, active_filters)

        elif choice == '5':  # Tech
            qs = {'q6_1': {'title': '[Q6.1] Game Features', 'options': OPT['q6_1'], 'func': Q6_1_Features_SQL}}
            if show_hard:
                qs['q6_2'] = {'title': '[Q6.2] Peripheral Support', 'options': OPT['q6_2'], 'func': Q6_2_Hardware_SQL}
            enter_sub_menu(conn,"Technology & Features", qs, active_filters)

        elif choice == '6':  # Price
            qs = {'q7_1': {'title': '[Q7.1] Price Range', 'options': OPT['q7_1'], 'func': Q7_1_Price_SQL},
                  'q7_2': {'title': '[Q7.2] DLC Preference', 'options': OPT['q7_2'], 'func': Q7_2_DLC_SQL}}
            enter_sub_menu(conn,"Price & DLC", qs, active_filters)

        elif choice == '7':  # Review & Time
            qs = {'q8_1': {'title': '[Q8.1] Review Rating', 'options': OPT['q8_1'], 'func': Q8_1_Review_SQL},
                  'q9_1': {'title': '[Q9.1] Playtime', 'options': OPT['q9_1'], 'func': Q9_1_Playtime_SQL},
                  'q9_2': {'title': '[Q9.2] Replay Factors', 'options': OPT['q9_2'], 'func': Q9_2_Replay_SQL}}
            enter_sub_menu(conn,"Reviews & Playtime", qs, active_filters)

        elif choice == '8':  # Compatibility
            qs = {'q10_1': {'title': '[Q10.1] Operating System', 'options': OPT['q10_1'], 'func': Q10_1_OS_SQL},
                  'q10_2': {'title': '[Q10.2] Language', 'options': OPT['q10_2'], 'func': Q10_2_Lang_SQL}}
            enter_sub_menu(conn,"Compatibility", qs, active_filters)

        elif choice == '9':  # Year
            qs = {'qf_1': {'title': '[QF.1] Release time', 'options': OPT['qf_1'], 'func': QF_1_Year_SQL}}
            enter_sub_menu(conn,"Release time", qs, active_filters)

    # --- 3. Query & Sort ---
    print("\n>>> Querying database...")
    final_ids = execute_intersect(conn, active_filters)

    print("\nSorting preferences: [1] Price [2] Positive reviews [3] New games")
    sort = get_user_input("sort", 3)
    if sort == 0: sort = 2

    show_final_results_sorted(conn, final_ids, sort)

    result_names = show_final_results_sorted(conn, final_ids, sort)
    conn.close()
    return result_names

# filter_game()

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.cm as cm



# DB_FILE_PATH = url

# Image Display
import logging

def show_visual_chart(results):
    """
    Suppress warnings + Display ID + Colab adaptation
    """
    if not results:
        print("❌ No data to visualize.")
        return

    # --- 1. Forcefully suppress all font warnings (Critical Step) ---
    # This line makes matplotlib silent
    logging.getLogger('matplotlib.font_manager').setLevel(logging.ERROR)

    # --- 2. Reset plotting parameters ---
    # Clear previously set 'SimHei' or 'Microsoft YaHei', restore default English
    plt.rcdefaults()

    # Create DataFrame
    df = pd.DataFrame(results)
    df_sorted = df.sort_values('PositiveRate', ascending=True)

    # Generate IDs
    df_sorted['DisplayID'] = [str(i) for i in range(1, len(df_sorted) + 1)]

    # Setup Canvas
    plt.figure(figsize=(12, 7))

    # Color Mapping
    norm = mcolors.Normalize(vmin=40, vmax=100)
    cmap = plt.get_cmap('RdYlGn')
    colors = cmap(norm(df_sorted['PositiveRate'].values))

    # Draw
    bars = plt.barh(df_sorted['DisplayID'], df_sorted['PositiveRate'], color=colors, alpha=0.8, edgecolor='black')

    # Labels
    plt.title('Game Positive Ratings (By ID)', fontsize=15, pad=15)
    plt.xlabel('Positive Rating (%)', fontsize=12)
    plt.ylabel('Game ID', fontsize=12)
    plt.xlim(0, 115)
    plt.grid(axis='x', linestyle='--', alpha=0.3)

    # Add text
    for bar in bars:
        width = bar.get_width()
        plt.text(width + 1, bar.get_y() + bar.get_height() / 2,
                 f'{int(width)}%', va='center', fontsize=10, fontweight='bold')

    plt.tight_layout()

    # --- 3. Print Legend ---
    print("\n" + "="*40)
    print("📋 CHART LEGEND ")
    print("="*40)
    print(f"{'ID':<5} | {'Game Name'}")
    print("-" * 40)
    for index, row in df_sorted.iloc[::-1].iterrows():
        print(f"{row['DisplayID']:<5} | {row['Name']}")
    print("="*40 + "\n")

    # --- 4. Since it's Colab, no need to close window ---
    print("✅ Chart generated below.")
    plt.show()
    print("\n⬇️ The program is still running... Please scroll down to see the subsequent input boxes. ⬇️")

# List of all available templates
ALL_TEMPLATES = [
    'developer_card',
    'type_positioning',
    'recent_popularity',
    'multi_platform_fit',
    'value_king',
    'comprehensive_recommendation'
]


def integrated_analysis_flow():
    """
    Integrated Flow: Filter -> Visual Option -> Select Game -> Select Identity -> Generate Report
    """

    # --- Step 1: Run filter to get list ---
    print("\n🚀 Starting Filter...")

    # This now returns a list of DICTIONARIES: [{'Name': 'CS:GO', 'PositiveRate': 90}, ...]
    game_data_list = filter_game()

    if not game_data_list:
        print("❌ No game list retrieved. Program terminating.")
        return

    # --- Step 1.5: Ask for Visualization (NEW FEATURE) ---
    print("\n" + "=" * 50)
    print("📊 Visualization Option")
    print("=" * 50)
    # Ask user if they want to see the chart
    show_chart = input(">> Do you want to see a Visual Chart of Positive Ratings? (y/n): ").strip().lower()

    # Modification: Ensure plot is closed after showing to prevent blocking
    if show_chart == 'y':
        try:
            show_visual_chart(game_data_list)
            plt.close('all') # Force close all plot windows
        except Exception as e:
            print(f"Chart rendering error (skipping): {e}")

    # 2. Buffer time for Colab UI rendering
    time.sleep(0.5)


    # --- Step 2: Select a game from the list ---
    print("\n" + "=" * 50)
    print("🎯 Please select a target game from the results for analysis")
    print("=" * 50)

    for index, item in enumerate(game_data_list):
        # item is now a dictionary, so we access ['Name']
        print(f"[{index + 1}] {item['Name']}")

    selected_game_name = ""
    while True:
        try:
            choice = input(f"\n>> Please enter number (1-{len(game_data_list)}): ")
            choice_idx = int(choice) - 1
            if 0 <= choice_idx < len(game_data_list):
                # Extract the name from the dictionary
                selected_game_name = game_data_list[choice_idx]['Name']
                print(f"✅ Selected Game: [{selected_game_name}]")
                break
            else:
                print("❌ Number out of range, please try again.")
        except ValueError:
            print("❌ Invalid input, please enter a number.")

    # --- Step 3: Select User Identity / Report Type ---
    print("\n" + "=" * 50)
    print("👤 Please select your identity or required report type")
    print("=" * 50)
    # -- Single Module Options --
    print("--- Single Module (Select one) ---")
    print("[1] Manufacturer's Card")
    print("[2] Type Positioning")
    print("[3] Recent Popularity")
    print("[4] Multi-platform Fit")
    print("[5] Value King")
    print("[6] Comprehensive Rec")

    # -- Bundle Options --
    print("\n--- Preset Bundles (Identity Mode) ---")
    print("[7] 🎮 Player Mode")
    print("    -> Includes: Value, Recent Popularity, Recommendation")
    print("[8] 🏭 Developer Mode")
    print("    -> Includes: Card, Positioning, Recent, Platform")
    print("[9] 📂 Full Report")
    print("    -> Generate ALL 6 modules")

    target_templates = []

    while True:
        role = input("\n>> Please select (1-9): ").strip()

        # === Single Mode (1-6) ===
        if role == '1':
            target_templates = ['developer_card']
            print("👉 Selected: Manufacturer's Business Card")
            break
        elif role == '2':
            target_templates = ['type_positioning']
            print("👉 Selected: Type Positioning")
            break
        elif role == '3':
            target_templates = ['recent_popularity']
            print("👉 Selected: Recent Popularity")
            break
        elif role == '4':
            target_templates = ['multi_platform_fit']
            print("👉 Selected: Multi-platform Compatibility")
            break
        elif role == '5':
            target_templates = ['value_king']
            print("👉 Selected: Cost Performance Analysis")
            break
        elif role == '6':
            target_templates = ['comprehensive_recommendation']
            print("👉 Selected: Comprehensive Recommendation")
            break

        # === Bundle Mode (7-9) ===
        elif role == '7': #
            print("📋 Configuring [Player Perspective] report templates...")
            target_templates = ['value_king', 'comprehensive_recommendation', 'recent_popularity']
            break

        elif role == '8': #
            print("📋 Configuring [Developer Perspective] report templates...")
            target_templates = ['developer_card', 'type_positioning', 'recent_popularity', 'multi_platform_fit']
            break

        elif role == '9': # Original Full Report
            print("📋 Configuring [Full Report] report templates...")
            target_templates = ALL_TEMPLATES # Use defined list containing all keys
            break

        else:
            print("❌ Invalid input. Please select a number from 1 to 9.")

    # --- Step 4: Call Report Generation Function ---
    print("\n" + "=" * 50)
    print(f"📠 Generating analysis report for [{selected_game_name}]...")
    print(f"📊 Selected Modules: {target_templates}")
    print("=" * 50)

    try:
        # Call your generation function
        generate_all_reports_for_game(
            game_name=selected_game_name,
            db_path=DB_FILE_PATH,
            select_templates=target_templates
        )
        print("\n✨ Report generation complete! Please check the output files.")

    except Exception as e:
        print(f"\n❌ Error during report generation: {e}")
        print("Please check database connection or ensure 'generate_all_reports_for_game' is defined correctly.")

def main_system_entry():
    """
    System Main Entry: Ask for user intent
    """
    db_path = url # Ensure url variable is accessible

    while True:
        print("\n" + "="*50)
        print("🎮 STEAM GAME DATA SYSTEM (Admin/User Mode)")
        print("="*50)
        print("[1] 🔍 Search & Analyze (Filter Dashboard)")
        print("[2] 🆕 Add New Game (Create)")
        print("[3] ✏️ Modify Game Price (Update)")
        print("[4] 🗑️ Delete Game (Delete)")
        print("[0] ❌ Exit System")
        print("="*50)

        choice = input(">> What would you like to do? (0-4): ").strip()

        if choice == '0':
            print("👋 Bye!")
            break

        elif choice == '1':
            # Call your complex analysis flow
            # Note: calling integrated_analysis_flow() directly
            # Ensure integrated_analysis_flow function doesn't contain sys.exit()
            integrated_analysis_flow()

        elif choice in ['2', '3', '4']:
            # Add/Delete/Update requires database connection
            conn = get_conn(db_path)
            if conn:
                if choice == '2':
                    add_new_game(conn)
                elif choice == '3':
                    update_game_price(conn)
                elif choice == '4':
                    delete_game(conn)
                conn.close()
            input("\nPress Enter to return to Main Menu...")

        else:
            print("❌ Invalid option.")


# main_system_entry(If you want to use this.py file alone, please delete the # in front)